import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import JSZip from "jszip";

export const runtime = "nodejs";

/**
 * GET /api/projects/:projectId/export
 * Export a project as a ZIP file
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ projectId: string }> }
) {
  try {
    const { projectId } = await params;

    if (!projectId) {
      return NextResponse.json(
        { error: "Missing projectId" },
        { status: 400 }
      );
    }

    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Fetch project metadata
    const { data: project, error: projectError } = await supabase
      .from("projects")
      .select("id, name, description, template_version")
      .eq("id", projectId)
      .eq("user_id", user.id)
      .single();

    if (projectError || !project) {
      return NextResponse.json(
        { error: "Project not found" },
        { status: 404 }
      );
    }

    // Fetch all files
    const { data: files, error: filesError } = await supabase
      .from("project_files")
      .select("path, content")
      .eq("project_id", projectId)
      .order("path");

    if (filesError) {
      console.error("Failed to fetch files:", filesError);
      return NextResponse.json(
        { error: "Failed to fetch project files" },
        { status: 500 }
      );
    }

    if (!files || files.length === 0) {
      return NextResponse.json(
        { error: "No files found in project" },
        { status: 404 }
      );
    }

    // Create ZIP file
    const zip = new JSZip();

    // Add all project files
    for (const file of files) {
      zip.file(file.path, file.content || "");
    }

    // Add setup instructions
    const setupInstructions = `# ${project.name}

${project.description ? project.description + "\n\n" : ""}## Setup Instructions

1. Install dependencies:
   \`\`\`bash
   npm install
   # or
   yarn install
   \`\`\`

2. Start the development server:
   \`\`\`bash
   npx expo start
   \`\`\`

3. Run on your device:
   - **iOS**: Scan the QR code with Camera app or use Expo Go
   - **Android**: Scan the QR code with Expo Go app
   - **Web**: Press 'w' in terminal

## Project Info

- **Generated with**: AppForge AI
- **Template Version**: ${project.template_version}
- **Project ID**: ${project.id}

## Documentation

Visit https://docs.expo.dev for more information about Expo and React Native.

---

Generated by AppForge AI - https://appforge.ai
`;

    zip.file("SETUP.md", setupInstructions);

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 9 },
    });

    // Return ZIP file as download
    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${project.name}.zip"`,
        "Content-Length": zipBuffer.length.toString(),
      },
    });
  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : "Failed to export project",
      },
      { status: 500 }
    );
  }
}
