-- Design Packages Table
-- Stores design packages generated by the Design Agent (Wizard or Express mode)

CREATE TABLE IF NOT EXISTS design_packages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  app_idea TEXT NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('wizard', 'express')),
  
  -- Design data
  feature_spec JSONB,
  branding JSONB,
  screens JSONB DEFAULT '[]',
  
  -- Wizard mode state
  wizard_state JSONB,
  
  -- Status
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'in_development')),
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_design_packages_user_id ON design_packages(user_id);
CREATE INDEX IF NOT EXISTS idx_design_packages_status ON design_packages(status);
CREATE INDEX IF NOT EXISTS idx_design_packages_created_at ON design_packages(created_at DESC);

-- RLS Policies
ALTER TABLE design_packages ENABLE ROW LEVEL SECURITY;

-- Users can view their own designs
CREATE POLICY "Users can view own design packages"
  ON design_packages
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can create designs
CREATE POLICY "Users can create design packages"
  ON design_packages
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own designs
CREATE POLICY "Users can update own design packages"
  ON design_packages
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Users can delete their own designs
CREATE POLICY "Users can delete own design packages"
  ON design_packages
  FOR DELETE
  USING (auth.uid() = user_id);

-- Updated timestamp trigger
CREATE OR REPLACE FUNCTION update_design_packages_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER design_packages_updated_at
  BEFORE UPDATE ON design_packages
  FOR EACH ROW
  EXECUTE FUNCTION update_design_packages_updated_at();
