/**
 * React Native Base Template
 *
 * This is the core template for all React Native projects generated by AppForge.
 * These files form the base structure that every project starts with.
 *
 * Version: 1.1.0
 * Last Updated: 2025-11-25
 */

export const TEMPLATE_VERSION = "1.1.0";

export interface TemplateFile {
  path: string;
  content: string;
  language: string;
  isCore: boolean; // Core files should not be modified by AI
}

/**
 * Get the base template files for a new React Native project
 */
export function getBaseTemplate(projectName: string, displayName: string): TemplateFile[] {
  return [
    {
      path: "package.json",
      language: "json",
      isCore: true,
      content: JSON.stringify(
        {
          name: projectName,
          version: "1.0.0",
          main: "expo-router/entry",
          scripts: {
            start: "expo start --web",
            android: "expo start --android",
            ios: "expo start --ios",
            web: "expo start --web",
            reset: "expo start --clear",
          },
          dependencies: {
            expo: "^54.0.0",
            "expo-router": "~6.0.0",
            "expo-status-bar": "~3.0.0",
            react: "19.1.0",
            "react-dom": "19.1.0",
            "react-native": "0.81.4",
            "react-native-web": "~0.21.2",
            "react-native-safe-area-context": "5.1.0",
            "react-native-screens": "~4.6.0",
            "expo-linking": "~7.0.0",
          },
          devDependencies: {
            "@types/react": "~19.0.10",
            typescript: "~5.8.3",
          },
        },
        null,
        2
      ),
    },
    {
      path: "app.json",
      language: "json",
      isCore: true,
      content: JSON.stringify(
        {
          expo: {
            name: displayName,
            slug: projectName,
            version: "1.0.0",
            scheme: projectName.replace(/-/g, ""),
            platforms: ["ios", "android", "web"],
            orientation: "portrait",
            icon: "./assets/icon.png",
            userInterfaceStyle: "automatic",
            splash: {
              image: "./assets/splash.png",
              resizeMode: "contain",
              backgroundColor: "#0f172a",
            },
            ios: {
              bundleIdentifier: `com.appforge.${projectName.replace(/-/g, "")}`,
              supportsTablet: true,
            },
            android: {
              package: `com.appforge.${projectName.replace(/-/g, "")}`,
              adaptiveIcon: {
                foregroundImage: "./assets/adaptive-icon.png",
                backgroundColor: "#0f172a",
              },
            },
            web: {
              favicon: "./assets/favicon.png",
              bundler: "metro",
            },
          },
        },
        null,
        2
      ),
    },
    {
      path: "tsconfig.json",
      language: "json",
      isCore: true,
      content: JSON.stringify(
        {
          extends: "expo/tsconfig.base",
          compilerOptions: {
            strict: true,
            paths: {
              "@/*": ["./*"],
            },
          },
          include: ["**/*.ts", "**/*.tsx", ".expo/types/**/*.ts", "expo-env.d.ts"],
        },
        null,
        2
      ),
    },
    {
      path: "app/_layout.tsx",
      language: "typescript",
      isCore: true,
      content: `import { Stack } from "expo-router";
import { StatusBar } from "expo-status-bar";

export default function RootLayout() {
  return (
    <>
      <Stack
        screenOptions={{
          headerShown: false,
          contentStyle: { backgroundColor: "#0f172a" },
        }}
      />
      <StatusBar style="light" />
    </>
  );
}
`,
    },
    {
      path: "README.md",
      language: "markdown",
      isCore: true,
      content: `# ${displayName}

Generated with AppForge AI - https://appforge.ai

## Get Started

1. Install dependencies:

   \`\`\`bash
   npm install
   # or
   yarn install
   # or
   pnpm install
   \`\`\`

2. Start the development server:

   \`\`\`bash
   npx expo start
   \`\`\`

## Run on Device

- **iOS**: Scan the QR code with the Camera app (iOS 11+) or use the Expo Go app
- **Android**: Scan the QR code with the Expo Go app
- **Web**: Press \`w\` in the terminal to open in browser

## Project Structure

\`\`\`
app/
├── _layout.tsx    # Root layout with navigation
└── index.tsx      # Main screen
\`\`\`

## Tech Stack

- **Expo SDK 54** - React Native framework
- **Expo Router 6** - File-based navigation
- **TypeScript 5.8** - Type safety
- **React 19 / React Native 0.81** - Latest runtime

## Template Version

This project was generated with AppForge template version ${TEMPLATE_VERSION}.
`,
    },
    {
      path: ".gitignore",
      language: "text",
      isCore: true,
      content: `# Expo
.expo/
dist/
web-build/

# Dependencies
node_modules/

# IDE
.vscode/
.idea/
*.sublime-*

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
.env*.local

# Debug
npm-debug.*
yarn-debug.*
yarn-error.*

# TypeScript
*.tsbuildinfo
`,
    },
    {
      path: ".npmrc",
      language: "text",
      isCore: true,
      content: `legacy-peer-deps=true
strict-peer-dependencies=false
auto-install-peers=true
fund=false
audit=false
engine-strict=false
`,
    },
  ];
}

/**
 * Check if a file path is part of the core template
 */
export function isCoreFile(path: string): boolean {
  const coreFiles = [
    "package.json",
    "app.json",
    "tsconfig.json",
    "app/_layout.tsx",
    "README.md",
    ".gitignore",
    ".npmrc",
  ];
  return coreFiles.includes(path);
}

/**
 * Get upgrade instructions when a new template version is available
 */
export function getUpgradeInstructions(fromVersion: string, toVersion: string): string {
  return `
## Template Upgrade Available

Your project is using template version ${fromVersion}.
A new template version ${toVersion} is available.

### What's New

- Updated dependency versions
- Improved configuration
- Enhanced project structure

### How to Upgrade

1. Review the changes in the new template
2. Backup your current project
3. Apply the upgrade from your dashboard

Note: Upgrading will only update core configuration files.
Your application code will remain unchanged.
  `.trim();
}
